export interface INovedad {
    codigoProductor: number,
    cuota: number,
    datoPago: string,
    fechaProcesamiento: string,
    frechazo: string,
    fvencimiento: string,
    idTransaccion: number,
    importe: number,
    medioPago: string,
    motivoRechazo: string,
    nombreProductor: string,
    nombreTomador: string,
    numeroPoliza: number,
    patente: string,
    producto: string,
    suplemento: number,
    vigenciaDesde: string,
}